//******************************************************************
//* Copyright (c) 2003-2009, Asiainfo HangZhou. All rights reserved.
//* SDL generated C++ implementation header file for OpenBOSS.
//* Source filename: ./idl/test.sdl
//* Generated date:  2014-05-16 14:04:53
//* Note: This is a auto-generated file, DON'T MODIFY IT!
//******************************************************************

#ifndef __OPEN_BOSS_INIT_TEST_SDL_INIT__
#define __OPEN_BOSS_INIT_TEST_SDL_INIT__

#include "compile.h"

extern "C" {

int32 INIT_G_MFIRSTTEST_ITESTHELLOWORLD_OUT_HELLOWORLD();

void FIN_G_MFIRSTTEST_ITESTHELLOWORLD_OUT_HELLOWORLD();

int32 INIT_T_MFIRSTTEST_ITESTHELLOWORLD_OUT_HELLOWORLD();

void FIN_T_MFIRSTTEST_ITESTHELLOWORLD_OUT_HELLOWORLD();

int32 INIT_G_MFIRSTTEST_IGETCYCLERUNDATA_QUERY_CYCLERUNDATA();

void FIN_G_MFIRSTTEST_IGETCYCLERUNDATA_QUERY_CYCLERUNDATA();

int32 INIT_T_MFIRSTTEST_IGETCYCLERUNDATA_QUERY_CYCLERUNDATA();

void FIN_T_MFIRSTTEST_IGETCYCLERUNDATA_QUERY_CYCLERUNDATA();

int32 INIT_G_MFIRSTTEST_IINSERTCYCLERUNDATA_INSERT_CYCLERUNDATA();

void FIN_G_MFIRSTTEST_IINSERTCYCLERUNDATA_INSERT_CYCLERUNDATA();

int32 INIT_T_MFIRSTTEST_IINSERTCYCLERUNDATA_INSERT_CYCLERUNDATA();

void FIN_T_MFIRSTTEST_IINSERTCYCLERUNDATA_INSERT_CYCLERUNDATA();
};

#endif

